version: '3.4'

volumes:
  next_node_modules:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - registration-api
      - registration-ui
    ports:
      - 7800:7800

  redis:
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    expose:
      - 6379

  registration-api:
    build: registration-api
    image: registration-api
    restart: 'no'
    volumes:
      - ./registration-api/:/app
      - ./app-cache/:/app-cache
    expose:
      - '7777-7778:7777'
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  registration-ui:
    build:
      context: registration-ui # Assuming your Next.js app code is in a 'web' directory
      dockerfile: Dockerfile # Make sure to have a Dockerfile in your 'web' directory
    image: registration-ui
    restart: 'no'
    volumes:
      - ./registration-ui/:/app
      - next_node_modules:/app/node_modules
    expose:
      - 3000
    depends_on:
      - registration-api

  database:
    container_name: database-server-dab-p1-b5e4c02f-784a-4080-95e7-6797c506c3c9
    image: postgres:14.1
    restart: 'no'
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env
